import Head from 'next/head';
import { Flex, Text } from '@chakra-ui/react';
import { ConnectButton } from '@rainbow-me/rainbowkit';

export default function Home() {
	return (
		<>
			<Head>
				<title>Fluid Bets</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Flex flexDir="column">
				<Text>Landing page</Text>
				<ConnectButton />
			</Flex>
		</>
	);
}
